In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,100,10)

In [4]:
arr

array([64, 28, 93, 99, 88, 31, 60, 36, 12, 26])

In [9]:
soa = arr[0:4].copy()

In [10]:
soa

array([64, 28, 93, 99])

In [11]:
soa[:]=100

In [12]:
soa

array([100, 100, 100, 100])

In [13]:
arr

array([64, 28, 93, 99, 88, 31, 60, 36, 12, 26])

In [1]:
import pandas as pd

In [15]:
country = ['USA','INDIA','UK']

In [16]:
pov_index = [1,13,2]

In [18]:
pd.Series(pov_index,country)

USA       1
INDIA    13
UK        2
dtype: int64

In [2]:
import numpy as np

In [3]:
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [4]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [5]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [6]:
mat[3,4]

20

In [7]:
mat[1,:3]

array([6, 7, 8])

In [8]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [13]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
mat.sum()

325

In [15]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [23]:
mat.std(axis=1)

array([ 1.41421356,  1.41421356,  1.41421356,  1.41421356,  1.41421356])